CREATE TABLE artist (
id VARCHAR(32) NOT NULL,
spotify_href VARCHAR(256) NOT NULL,
name VARCHAR(300) NOT NULL,
genre VARCHAR(255) NOT NULL,
CONSTRAINT PK_ARTIST_ID PRIMARY KEY(id),
CONSTRAINT UQ_ARTIST_SPOTIFY_HREF UNIQUE(spotify_href)
);

CREATE TABLE album (
id VARCHAR(32) NOT NULL,
primary_artist_id VARCHAR(32) NOT NULL,
spotify_href VARCHAR(256) NOT NULL,
name VARCHAR(300) NOT NULL,
image VARCHAR(512) NOT NULL,
duration_ms BIGINT NOT NULL,
release_date DATETIME NOT NULL,
CONSTRAINT PK_ALBUM_ID PRIMARY KEY(id),
CONSTRAINT FK_ALBUM_PRIMARY_ARTIST_ID FOREIGN KEY (primary_artist_id) REFERENCES artist(id),
CONSTRAINT UQ_ALBUM_SPOTIFY_HREF UNIQUE (spotify_href)
);

CREATE TABLE track (
id VARCHAR(32) NOT NULL,
album_id VARCHAR(32) NOT NULL,
spotify_href VARCHAR(256) NOT NULL,
name VARCHAR(300) NOT NULL,
explicit BOOLEAN DEFAULT FALSE NOT NULL,
duration_ms BIGINT NOT NULL,
popularity TINYINT NOT NULL,
track_number SMALLINT NOT NULL,
CONSTRAINT PK_TRACK_ID PRIMARY KEY(id),
CONSTRAINT FK_TRACK_ALBUM_ID FOREIGN KEY(album_id) REFERENCES album(id),
CONSTRAINT UQ_ALBUM_SPOTIFY_HREF UNIQUE (spotify_href)
);